import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils"
import { Toaster } from "@/components/ui/toaster"
import Sidebar from "@/components/sidebar";
import { User } from "lucide-react";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          raleway.className
        )}
      >
        <div className="flex w-full min-h-screen">
          <Sidebar />
          <div className="flex flex-col w-full min-h-screen">
            <header className="flex items-center p-4 justify-end">
            </header>
            {children}
          </div>
        </div>
        <Toaster />
      </body>
    </html>
  );
}